### PR TITLE
Feature/optimized list loading

### PR DESCRIPTION
**Pull request by toirl**
This PR will introduce "optimzed" loading of items under certain conditions when using paginated overviews.
Optimized loading means that we will delegate as much as work as possible to the database and reduce the amount of work left to the application. e.g only process the relevant 25 paginated elements.

Currently only the default overview is supported. If any sorting or searching comes in place the application will fallback into its old behavior and will do all the work in the application.

### CODE REVIEW

**Comment by toirl** [comment]
@matakuka can you please check if this PR brings a significant performance boost for the default paginated overview (without explicit sorting or searching)

**Comment by matakuka** [comment]
@toirl For me, it gives a internal server error as soon as I open any list:
```
  File "/usr/lib/python2.7/site-packages/ringo-1.17.0-py2.7.egg/ringo/model/base.py", line 735, in paginate
    if total == len(self.items):
TypeError: object of type 'CachingQuery' has no len()
```

**Comment by toirl** [comment]
@matakuka Can not reproduce this issue even I have the same line of code here. I am not sure if I missed to push some commits

**Comment by matakuka** [comment]
Works now; apparently I had something in an unclean state.

**Comment by matakuka** [comment]
I can confirm that the changes in this branch speeds the performance of lists greatly (factor 3 to 4), bringing most paginated lists to a total loading time of less than two seconds.

The effect diminishes with great pagination numbers, at pagination of 500 the improvement shrinks to about 20%. Which is still an improvement.

**Comment by toirl** [comment]
Thanks for the reply and confirmation of the intended improvement.

**Pull request merged**
