### PR TITLE
added  proper check for classes

### PR DESCRIPTION
**Pull request by matakuka**
Hmpf. I had to chose:
- The Jquery function `hasClass` is not working, because it is _not_ a jquery object.
- Or the javascript function `hasAttribute` is not working, because it _is_ a jquery object.

I went for the first one, and check the classes like how jquery does it anyway.

### CODE REVIEW

**Comment by matakuka** [comment]
@tjunk Apparently I cannot request reviews, so I am requesting by this commentary.

**Comment by matakuka** [comment]
Closing this, as some project needs an older version due to supporting Ancient Browsers from the Dark Ages.

**Comment by toirl** [comment]
I do not understand the reason why this PR is closed.

**Comment by matakuka** [comment]
I closed it because after discussion it became clear that we need another approach. Changing the code  and changing back would be distracting in commit history, that's why I prefer to do the same thing in another branch. The original issue is still open, so no information lost on closing this

**Comment by matakuka** [comment]
See #75

**Pull request closed without merging**
