### PR TITLE
Sqlalchemy cleanup

### PR DESCRIPTION
**Pull request by g-tom**
Two more sqlalchemy-related improvements. See the commit messages for details.

### CODE REVIEW

**Review by toirl — APPROVED** [review]

**Review by toirl — COMMENTED** [review]
This change may break other applications in case they refer to profile[0].

You can/must check this with: find . -type f | xargs grep "profile\[0\]"

**Comment by g-tom** [comment]
> You can/must check this with: find . -type f | xargs grep "profile[0]"

... which finds things in Caches in my case. Something like `./data/sessions/data/container_file/${some_maybe_random_string}.cache:Vprofile[0].first_name`

Maybe existing sessions will be compromised?

**Comment by ThomasJunk** [comment]
@toirl FYI
[occurances.txt](https://github.com/ringo-framework/ringo/files/1318795/occurances.txt)

**Comment by g-tom** [comment]
Just amended the commit with a note in CHANGES.txt: 0aba358

**Comment by toirl** [comment]
I am fine with merging this change after we made the upgrades in other projects (eFa) which still rely on the old notation.

This PR should result in a new version, which clearly indicates that using this version requires others to adapt their code.

I assigned this PR to @ThomasJunk as he knows best when the other projects has been upgraded.

**Pull request closed without merging**
