### PR TITLE
Fix error handling

### PR DESCRIPTION
**Pull request by g-tom**
Consider the case where a Ringo-based application has a model class with a method decorated with [@validates](http://docs.sqlalchemy.org/en/latest/orm/mapped_attributes.html#sqlalchemy.orm.validates), which raises an AttributeError in certain cases. BaseItem.set_values() used to catch that AttributeError and hide it behind a misleading warning, if use_strict=False, or raised an AttributeError with a misleading message, if use_strict=True. In case this happened when using an admin-script, the warning did even not appear. @ThomasJunk has seen the concrete example, too. Other scenarios with AttributeErrors raising elsewhere than expected might be conceivable. Thus b37cf84f0dcefd8bad04573f2feeaca4a34721c1.

In passing a bit of API-clearance with 82fe1467452a3395c68fdda0cab4e389de22d64c.

### CODE REVIEW

**Comment by g-tom** [comment]
Remark from toirl about 82fe1467452a3395c68fdda0cab4e389de22d64c:

`get_item_factory()` might be overwritten in other Ringo-based applications. In these cases, at least an import will fail because the overwritten functions have no argument `use_strict.` In order to not break these applications, backwards compatibility should be ensured before merging this PR.

**Comment by toirl** [comment]
@g-tom I don't remind it clearly. Did we agreed on adding  compatiblility code and some depercated warning in case the "overwritten" get_item_factory method does not provide a use_string param?

**Comment by g-tom** [comment]
> Did we agreed on adding compatiblility code and some depercated warning

Yes.

**Comment by g-tom** [comment]
b37cf84 and 82fe146 went to another upstream (https://bitbucket.org/intevation/ringo/commits/f9eeba84b9369a0d2178f5131b6b7c80887b68c1; https://bitbucket.org/intevation/ringo/commits/03398df0928b59bcce2b0ccb7e2dcd5a66077580)

**Pull request closed without merging**
